name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_TOKEN}}
      - name: Start services
        run: docker-compose up -d
      - name: Test
        run: docker-compose exec app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose exec app sh -c "flake8"
      - name: Stop services
        run: docker-compose down
