name: Checks

on: [push]  # Trigger workflow on pushes to any branch

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04  # Specify the runner environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use actions/checkout action for clean checkout

      - name: Login to Docker Hub (optional)
        uses: docker/login-action@v1  # Use docker/login-action for authentication
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image (optional)
        uses: docker/build@v1  # Use docker/build action to build the image
        with:
          context: .  # Use the current directory as the build context
          dockerfile: ./Dockerfile  # Specify the path to your Dockerfile

      - name: Run tests
        uses: docker/compose@v2  # Use docker/compose action to run tests
        with:
          service: app  # Specify the service to run tests within
          command: python manage.py test  # Specify the command to run

      - name: Run linting
        uses: docker/compose@v2  # Use docker/compose action to run linting
        with:
          service: app  # Specify the service to run linting within
          command: flake8  # Specify the command to run